/*
package review12;

public class ExceptionDemo2 {

    public static void main(String[] args) {

        String name = "!Batch 15 is smart";
        try {
            System.out.println(name.charAt(-1));
        } catch () {

            System.out.println("rest of the program");

        }


    }
}
*/
